### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/laravel-frontend-presets/tall/pull/100/commits/2517e9d8f7f9e93ea97e9b002ed17fbe2c6c153c?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/tall.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "laravel-frontend-presets/tall": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by DominikGeimer** [comment]
Tried the Shift Repo. Looks good.

**Comment by danharrin** [comment]
It's bumped the minimum version though... which is weird. would have thought it added it as another.

**Comment by jasonmccreary** [comment]
@danharrin, it's based on the previous support level, which was the "latest version".

**Comment by danharrin** [comment]
> Tried the Shift Repo. Looks good.

The tests are failing for Laravel 9, so this is going to need some more investigation. I am more than happy to handle this, or if it is helpful to @jasonmccreary then he can use the failed tests to improve the L9 Shift :)

**Comment by ryangjchandler** [comment]
@danharrin Looks like the configuration of the tests is wrong, will take a look later.

**Comment by danharrin** [comment]
It's not just the missing sender address, it's also the fact that the `password` rule has been renamed to `current_password`.

**Comment by ryangjchandler** [comment]
@danharrin We should probably just use `9.x` then and look at moving to TW 3 too.

**Comment by danharrin** [comment]
Sure. I think the package needs a rewrite anyway. Add some rate limiting and everything.

**Comment by danharrin** [comment]
New design

**Pull request merged**
