### PR TITLE
change path and routes

### PR DESCRIPTION
**Pull request by bhargavraviya**
- wrong file name stubs/default/postcss.config.cjs to postcss.config.js
- Change of Laravel Livewire 3 path on the folder
- change in routes of effect Livewire 3 (new)
- change: add a logout button on the welcome.blade.php page

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, please fix the tests

**Comment by bhargavraviya** [comment]
Hi @danharrin , there is no issue in your test case, but in your test case system, it shows an error.
https://github.com/laravel-frontend-presets/tall/actions/runs/5707042038/job/15464764322
please guide me on how to solve this.

**Comment by danharrin** [comment]
I think you need to replace the strings like `auth.login` with the full class name `Login::class` for LW3 @bhargavraviya

**Comment by bhargavraviya** [comment]
> auth

thank you for the replay I have changed the test case please check again if it is correct or not

**Comment by bhargavraviya** [comment]
@danharrin
Any test case error is pending please guide me

**Comment by johnpbloch** [comment]
@bhargavraviya I think the workflow file (`.github/workflows/tests.yml`) needs to be updated to install v3 of livewire under the "Install Dependencies" step.

**Comment by bhargavraviya** [comment]
> @bhargavraviya I think the workflow file (`.github/workflows/tests.yml`) needs to be updated to install v3 of livewire under the "Install Dependencies" step.

I have already livewire v3

**Comment by johnpbloch** [comment]
Yes, but the test runner in GitHub actions doesn't.

- Open `.github/workflows/tests.yml` in your editor.
- Go to line 37
- Change `^2.0` to `^3.0`
- Commit the change and push to this pull request branch

Tests will pass for this PR after that.

**Comment by bhargavraviya** [comment]
I have changes Done 

@johnpbloch  please check and merged it

**Comment by johnpbloch** [comment]
@danharrin will have to take care of that.

**Pull request merged**
