### PR TITLE
Update NPM Dependencies

### PR DESCRIPTION
**Pull request by danharrin**
Solves #86 (hopefully).

Both @ryangjchandler and I are unable to reproduce the original issue so hopefully bumping all NPM dependencies to their latest versions should help out.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@danharrin Is it worth targeting a patch release for this, instead of a minor release?

**Comment by danharrin** [comment]
Hmm I've bumped the minor releases of quite a few dependencies and added new ones, I think a minor might be a safer bet 🤔

**Comment by ryangjchandler** [comment]
> Hmm I've bumped the minor releases of quite a few dependencies and added new ones, I think a minor might be a safer bet 🤔

I'm not fussed either way!

**Review by ryangjchandler — APPROVED** [review]

**Comment by nathandaly** [comment]
Latest node `15.6.0` and npm version`7.4.0`.

```bash
    ~/Projects/Nathan/Web/tall-dep  php artisan ui tall --auth                                                                                                                                                                                                                                        ✔  at 00:06:59 
TALL preset scaffolding installed successfully.
Auth scaffolding installed successfully.
Please run "npm install && npm run dev" to compile your new assets.

    ~/Projects/Nathan/Web/tall-dep  npm install                                                                                                                                                                                                                                                       ✔  at 00:07:28 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: laravel-mix@6.0.10
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^6.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev laravel-mix-tailwind@"^0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: laravel-mix@2.1.14
npm ERR! node_modules/laravel-mix
npm ERR!   peer laravel-mix@"^2.1.7" from laravel-mix-tailwind@0.1.1
npm ERR!   node_modules/laravel-mix-tailwind
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/nathandaly/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathandaly/.npm/_logs/2021-01-16T00_07_34_635Z-debug.log
```

**Pull request merged**
