### PR TITLE
Added laravel 11 support

### PR DESCRIPTION
**Pull request by marufmax**
Summary:
- updated php version
- updated laravel, laravel ui and phpunit versions 
- updated tests and stubs to comply with Laravel 11

### CODE REVIEW

**Comment by danharrin** [comment]
Please remove Laravel 10 support as this package should only be used in new projects. Please update the GitHub tests workflow too.

**Comment by marufmax** [comment]
@danharrin, good point. removed backward compatibility and updated the GitHub action

**Comment by tafarelyan** [comment]
Any updates in this pull request?

**Comment by NoelisTired** [comment]
I'd like to use this pull, i do however not know how to directly integrate branch this in my app :(

**Comment by danharrin** [comment]
Thanks @marufmax

**Pull request merged**
