### PR TITLE
Use Livewire's routing helper

### PR DESCRIPTION
**Pull request by pktharindu**
I noticed a lot of views that only return a Livewire component, which I think is redundant.

This PR uses Livewire's routing helper to cut out the extra boilerplate code.

PS: There are some CS fixes as well. 😄

### CODE REVIEW

**Comment by DanHarrin** [comment]
Hey, please remove these CS fixes for now and put them in another PR so we can analyse their relevance separately. Thanks.

**Comment by pktharindu** [comment]
Done 🚀

**Comment by imliam** [comment]
This was something we intentionally avoided before, as we figured it'd be easier for people to understand the existing `@extends()` behaviour in Blade instead of having part of the view layout determined by the routing. That said, it definitely does add a lot of boilerplate that is pretty ugly to get around, you're right.

Would it be feasible to use `Route::layout('layouts.auth')->group(...)` instead of defining it on every single one?

**Comment by pktharindu** [comment]
Actually, that is the first thing I tried. But I don't think that is a thing. Though I wish Livewire had such functionality.

**Comment by DanHarrin** [comment]
@pktharindu @imliam using a route group like that does work. That would be my preferred direction.

**Comment by pktharindu** [comment]
Sorry, by bad. You guys are right. 🤦🏼‍♂️

I could have sworn I got an error last time I tried. But seems to be working fine now.

**Comment by imliam** [comment]
FYI, you can do `Route::layout()->middleware()->group()` just fine, but `Route::middleware()->layout()->group()` throws an error - I see how you could've got that error before

**Comment by DanHarrin** [comment]
Odd bug, I'll add that to my todos 😅.

**Comment by codytooker** [comment]
This was the first thing I did when using this preset. However the one thing you miss doing it this way is the title tag in the `layouts.base` file.  

You can get this functionality back by adding the following to `layouts.auth`

```
@if (isset($title))
   @section('title', $title)
@endif
```

then for your routes you can do something like the following

```
Route::livewire('/login', 'auth.login')->layout('layouts.auth', [
    'title' => 'Sign in to your account'
  ])->name('login');
```

**Comment by imliam** [comment]
Thanks for the PR, that cleans up a few files ❤️

**Pull request merged**
