### PR TITLE
Allow running under PHP 8.

### PR DESCRIPTION
**Pull request by mikebronner**
This PR changes the PHP version constant to not be restricted to 7.x, but instead allow anything greater than 7.2.5.

### CODE REVIEW

**Comment by imliam** [comment]
This is not the correct way to denote version support in Composer. There is no guarantee this package will work on future versions like PHP 9, as far away as that may sound.

If you're to add PHP 8 support, could you denote the version constraints properly in the composer.json file (`^7.2.5|^8.0`) and make sure to update the workflow file to run the tests on PHP 8 to prove it works too.

**Comment by mikebronner** [comment]
So changed. Let me know if I missed anything.

**Comment by imliam** [comment]
Thanks, much better now! Merged.

**Comment by lupinitylabs** [comment]
Any chance to release this change? I would hate to require dev-master.

**Comment by danharrin** [comment]
@lupinitylabs All done :)

**Comment by lupinitylabs** [comment]
> 
> 
> @lupinitylabs All done :)

Awesome, thank you very much :))

And Merry Christmas to you... :grinning:

**Pull request merged**
