### PR TITLE
Add loading state to buttons

### LINKED ISSUE #16: Add a spinner while loading
A visual clue would be helpful while livewire is doing something in the background.

I recommend the [tailwind spinner plugin](https://github.com/aniftyco/tailwindcss-spinner) for this purpose.
I'd be willed to create a PR if any of the maintainers (I assume @imliam and @DanHarrin) approve the usage of an additional tailwind plugin.

### PR DESCRIPTION
**Pull request by Wulfheart**
Closes #16. Adds a loading state to the buttons with no external dependencies.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Thanks for contributing @Wulfheart! I've modified the description a little so the issue get closed when merged :)

**Comment by pktharindu** [comment]
Submit buttons are still clickable when loading.
Maybe we could also add `disabled` attribute on `wire:loading` to prevent multiple submits?

**Comment by DanHarrin** [comment]
That's a good call, @pktharindu.

@Wulfheart Should be solvable with `wire:loading.attr="disabled"` on the buttons.

**Comment by Wulfheart** [comment]
Thanks for noting it. I will update it.

**Comment by nasyrov** [comment]
@Wulfheart perhaps it would be good to add 'disabled' attribute to buttons as well

```blade
<button wire:loading.attr="disabled">
    Submit
</button>
```

**Comment by Wulfheart** [comment]
@nasyrov thanks for your notice. I’m unsure how your proposal is different to the on @DanHarrin made above.
I’m still on it. Just a little lack of time. 😅

**Comment by ryangjchandler** [comment]
Hey @wulfheart, have you had a chance to look at the improvements above?

**Comment by Wulfheart** [comment]
@ryangjchandler To be honest I forgot about it.  

By the way: What are the pros of using livewire for user login?

**Pull request closed without merging**
