### PR TITLE
Only send verification email if User model implements MustVerifyEmail

### PR DESCRIPTION
**Pull request by stancl**
😘

### CODE REVIEW

**Comment by xewl** [comment]
Isn't this something that gets triggered by the `\Illuminate\Auth\Events\Registered` event anyway?

**Comment by stancl** [comment]
Seems like the right way to do this. I'll let maintainers decide.

**Comment by DanHarrin** [comment]
Yes, I can see #29 being a better solution for this.

**Comment by imliam** [comment]
Closed as #29 is merged

**Pull request closed without merging**
